### PR TITLE
[feat] Print test file in the failure info

### LINKED ISSUE #3167: Print test file in the failure info
It is useful for locating the test in order to understand its logic in case of failures.

### PR DESCRIPTION
**Pull request by Blanca-Fuentes**
Prints the name of the file where the failing test is located in the failure info.

Closes #3167.

### CODE REVIEW

**Comment by vkarak** [comment]
Could you rebase your PR on `master`, since this is not a new feature or related to an upcoming feature. Check also the [Contribution Guidelines](https://github.com/reframe-hpc/reframe/wiki/Contributing-to-ReFrame) to better understand the concept of each of the two major branches.

**Review by vkarak — CHANGES_REQUESTED** [review]
Could you rebase your PR on master, since this is not a new feature or related to an upcoming feature. Check also the [Contribution Guidelines](https://github.com/reframe-hpc/reframe/wiki/Contributing-to-ReFrame) to better understand the concept of each of the two major branches.

**Comment by Blanca-Fuentes** [comment]
I also made the change in master (cf9509aa3977438f7af0e106b67c12a65ab2009b) but this summary is printed from a different file which does not exist anymore in develop. Should I do two separate PRs for master and develop?

**Comment by vkarak** [comment]
No need for this, we will fix the conflict once we merge master into develop.

**Pull request closed without merging**
