### PR TITLE
[test] Add optional validation `-c` option to the OSU hpclib tests

### PR DESCRIPTION
**Pull request by mszpindler**
I would like to propose optional `validation` parameter for the checks class that enables built-in OSU validation.

### CODE REVIEW

**Comment by ekouts** [comment]
Ok to test

**Review by vkarak — COMMENTED** [review]
That's a good proposal and I would propose to replace our current validation completely. It's always better to use the benchmark's validation. @rsarm What do you think?

**Comment by rsarm** [comment]
I agree. I think it's a good idea. @mszpindler had told me about it offline.

**Review by vkarak — CHANGES_REQUESTED** [review]

**Comment by vkarak** [comment]
@mszpindler I have made a PR to your branch with my suggestion to use always the `-c` option. Could you please merge it, so that we can merge this one as well?

**Comment by vkarak** [comment]
Replaced by #2679.

**Pull request closed without merging**
