### PR TITLE
[bugfix] Evaluate Slurm job nodelist lazily

### LINKED ISSUE #3018: Nodelist not properly logged in perflog
Hi I found this closed issue #2567 but I think I'm running into the same problem. 
Problem: if I run a run only regression test on multiple nodes I currently only get the first startup node logged in my reframe perflog. I read in the issue mentioned above that the issue was, that 'sacct' wasn't called multiple times. But by running in debug mode '-v -v -v' reframe seems to call 'sacct' multiple times during the run and if I call the same 'sacct' command in a second terminal I get the correct nodelist.  
I have the following setup: 
scheduler: slurm, 
launcher:mpirun
ReFrame-HPC  4.4.0 

```
 'logging': [
        {
            'level': 'debug',
            'handlers': [
                {
                    'type': 'stream',
                    'name': 'stdout',
                    'level': 'info',
                    'format': '%(message)s'
                },
                {
                    'type': 'file',
                    'level': 'debug',
                    'format': '[%(asctime)s] %(levelname)s: %(check_info)s: %(message)s',   # noqa: E501
                    'append': False
                }
            ],
            'handlers_perflog': [
                {
                    'type': 'httpjson',
                    'url': <url>,
                    'level': 'info'
                },
                {
                    'type': 'filelog',
                    'prefix': '%(check_system)s/%(check_partition)s',
                    'level': 'info',
                    'format': (
                        '%(check_job_completion_time)s|'
                        'reframe %(version)s|'
                        '%(check_info)s|'
                        '%(check_jobid)s|'
                        '%(check_job_nodelist)s|'
                        '%(check_num_tasks)s|'
                        '%(check_num_cpus_per_task)s|'
                        '%(check_num_tasks_per_node)s|'
                        '%(check_num_gpus_per_node)s|'
                        '%(check_perfvalues)s|'
                        '%(check_spack_spec)s|'
                        '%(check_display_name)s|'
                        '%(check_system)s|'
                        '%(check_partition)s|'
                        '%(check_environ)s|'                       
                        '%(check_extra_resources)s|'
                        '%(check_env_vars)s|'
                        '%(check_tags)s'
                    ),
                    'format_perfvars': (
                        '%(check_perf_value)s|'
                        '%(check_perf_unit)s|'
                        '%(check_perf_ref)s|'
                        '%(check_perf_lower_thres)s|'
                        '%(check_perf_upper_thres)s|'
                    ),
                    'append': True
                }
            ]
        }
    ],


```

### PR DESCRIPTION
**Pull request by vkarak**
The `nodelist` evaluation was being triggered early by logging, when we update the log record with all the test attributes:

https://github.com/reframe-hpc/reframe/blob/b1c89701d37f9378cf010f9271c7be312cb30e17/reframe/core/logging.py#L832-L846

The problem is that in some cases Slurm does not populate the nodelist of the job immediately, so we might end with an incomplete node list in the test job. We fix this by evaluating lazily the job's nodelist after the job has finished.

Fixes #3018.

@stefaniereuter could you please check if this fixes your problem?

### CODE REVIEW

**Comment by stefaniereuter** [comment]
Thank you so much @vkarak. I will try this as soon as our system is back from maintenance.

**Comment by vkarak** [comment]
@stefaniereuter did you manage to try this out?

**Comment by stefaniereuter** [comment]
I am so sorry I haven't had a chance to test yet as our system will still be down for probably another week.

26 Oct 2023 14:49:16 Vasileios Karakasis ***@***.***>:

**Review by ekouts — APPROVED** [review]

**Comment by vkarak** [comment]
@stefaniereuter Did you have a chance to test this? We will merge this PR so as to make it to the 4.4.1 release. If the problem is not fixed, feel free to reopen the issue.

**Comment by stefaniereuter** [comment]
sorry for the very late response. Yes we were finally able to test this last week and it seem to fix our issue, thank you so much

**Pull request merged**
