### PR TITLE
[doc] Adapt README for dark and light Github modes

### LINKED ISSUE #2204: ReFrame logo in README does not show up correctly in Github's dark mode
Screenshot:

image (1)

Thanks @branfosj for spotting this.

### PR DESCRIPTION
**Pull request by ekouts**
@rsarm found an example from DeepSpeed's README.md https://github.com/microsoft/DeepSpeed/blob/master/README.md

You can see directly how it looks in https://github.com/ekouts/reframe/tree/dark_logo

(Hadn't noticed that there was an issue and a slightly different solution from Teo actually 😅)
Closes #2204

### CODE REVIEW

**Review by rsarm — APPROVED** [review]

**Comment by ekouts** [comment]
I close it so that I don't spam you with my tries, the suggested way doesn't work for me for some reason.

**Comment by teojgo** [comment]
> In the documentation of github they suggest the `<picture>` element but i couldn't make it work. I think for now `#gh-dark-mode-only` and `#gh-light-mode-only` are good enough.

The only problem that this has, is that because we extract the logo for the pypi installation via the README, it will show the logo twice.

**Comment by ekouts** [comment]
> The only problem that this has, is that because we extract the logo for the pypi installation via the README, it will show the logo twice.

Aha, is that why we also had `https://raw.githubusercontent.com/reframe/...` paths instead of of relevant paths? Do you know if the picture element would solve the problem?

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by ekouts** [comment]
I added an second README.md for pypi. It has the old picture so it should appear normally. It is not a great solution, because we have to maintain two READMEs, almost identical other that the picture on top. Any better idea?

**Comment by teojgo** [comment]
> I added an second README.md for pypi. It has the old picture so it should appear normally. It is not a great solution, because we have to maintain two READMEs, almost identical other that the picture on top. Any better idea?

For me it's fine. I don't know how else it could work.

**Comment by vkarak** [comment]
@ekouts @teojgo Couldn't that second README be generated on the fly before deployment to PyPI?

**Comment by teojgo** [comment]
> @ekouts @teojgo Couldn't that second README be generated on the fly before deployment to PyPI?

yes but this would need to happen from the github action before publishing, but I would like to avoid forgetting to update the corresponding github action if the README changes

**Comment by vkarak** [comment]
> but I would like to avoid forgetting to update the corresponding github action if the README changes

Wouldn't you have the same problem with maintaining a copy of the README in parallel? How can we make sure that the copy is always updated. That's why I proposed to generate the PyPI README just before publishing if possible?

**Comment by ekouts** [comment]
In my opinion the pypi readme is not that important and we don't even need to have all the information from github. What if we have a more minimal readme for pypi that has the `nutshell` section + links to github and docs + the contact section about mailing list + slack etc. Like this we won't have to generate and we avoid mentioning something that is not up-to-date.

**Comment by vkarak** [comment]
Perhaps rename it to `README_minimal.md` instead of `README_pypi.md`.

**Review by vkarak — APPROVED** [review]

**Pull request merged**
